- name: Documentazione di Docker
  href: index.yml
- name: Guida introduttiva
  expanded: true
  items:
    - name: Distribuire una macchina virtuale Ubuntu con Docker
      href: 'https://azure.microsoft.com/resources/templates/docker-simple-on-ubuntu/'
- name: Esercitazioni
  items:
    - name: App Web Python con Docker e PostgreSQL
      href: ../app-service/tutorial-python-postgresql-app.md?toc=%2fazure%2fpostgresql%2ftoc.json
    - name: 'Integrazione continua e distribuzione continua con Docker, Jenkins e Linux'
      href: /azure/developer/jenkins/pipeline-with-github-and-docker
- name: Guide pratiche
  items:
    - name: Estensione della macchina virtuale Docker
      href: 'https://github.com/Azure/azure-docker-extension/blob/master/README.md'
    - name: Computer Docker
      href: ../virtual-machines/linux/docker-machine.md
    - name: Registro contenitori di Docker
      href: ../container-registry/container-registry-get-started-portal.md
- name: Risorse
  items:
    - name: Roadmap per Azure
      href: 'https://azure.microsoft.com/roadmap/'
    - name: Driver di Docker per Azure
      href: 'https://docs.docker.com/machine/drivers/azure/'
    - name: Sito di Docker per Azure
      href: 'https://www.docker.com/docker-azure'
    - name: Sito di Docker
      href: 'https://docker.com'