- name: Ansible in Azure
  href: ./index.yml
- name: Panoramica
  items:
    - name: Informazioni su Ansible in Azure
      href: ./ansible-overview.md
- name: Guide introduttive
  expanded: true
  items:
    - name: Installare e configurare Ansible
      href: /azure/virtual-machines/linux/ansible-install-configure
      maintainContext: true
    - name: Creare una macchina virtuale Linux
      href: /azure/virtual-machines/linux/ansible-create-vm
      maintainContext: true
- name: Esercitazioni
  items:
    - name: Creare una VM Linux completa
      href: /azure/virtual-machines/linux/ansible-create-complete-vm
      maintainContext: true
    - name: Eseguire un playbook in Cloud Shell
      href: ./ansible-run-playbook-in-cloudshell.md
      maintainContext: true
    - name: Gestire gli inventari dinamici
      href: ./ansible-manage-azure-dynamic-inventories.md
      maintainContext: true
- name: Riferimenti
  items:
    - name: Ruoli dei playbook
      items:
        - name: azure_module
          href: 'https://galaxy.ansible.com/Azure/azure_modules/'
        - name: azure_preview_module
          href: 'https://galaxy.ansible.com/Azure/azure_preview_modules'
    - name: Versioni e funzionalit√†
      href: ./ansible-matrix.md
    - name: Istanze di contenitore di Azure
      href: 'http://docs.ansible.com/ansible/latest/azure_rm_acs_module.html'
    - name: Funzioni di Azure
      href: 'http://docs.ansible.com/ansible/latest/azure_rm_functionapp_module.html'
    - name: Servizi di bilanciamento del carico
      href: 'http://docs.ansible.com/ansible/latest/azure_rm_loadbalancer_module.html'
    - name: Macchine virtuali
      href: 'http://docs.ansible.com/ansible/latest/azure_rm_virtualmachine_module.html'
    - name: Tutti i moduli per Azure
      href: 'http://docs.ansible.com/ansible/latest/list_of_cloud_modules.html#azure'